INSERT INTO USERS(USERNAME, PASSWORD) VALUES ('nando-cezar1', '1234');
INSERT INTO USERS(USERNAME, PASSWORD) VALUES ('nando-cezar2', '1234');
INSERT INTO TIPS(TITLE, PHOTO, TEXT, CATEGORY) VALUES ('Titulo da dica', 'Url foto da dica', 'Texto da dica', 'DIETS');
INSERT INTO COMMENTS(DATE_TIME, TEXT, USER_ID, TIP_ID) VALUES ('2018-01-07T16:11:26.485', 'Conteudo do comentário', 1, 1);
INSERT INTO COMMENTS(DATE_TIME, TEXT, USER_ID, TIP_ID) VALUES ('2018-01-07T16:11:26.485', 'Conteudo do comentário', 2, 1);

